theme: jekyll-theme-cayman
relative_links:
  enabled: true
  collections: true
language: english
include:
  - README.md
  - LICENSE.md
  - .github*
  - CODE_OF_CONDUCT.md
  - DOCUMENTATION.md
  - API_DOCUMENTATION.md
  - GETTING_STARTED.md

